// Generated by scripts/build-locations.mjs; do not edit.
export default {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -113.5684606,
          37.1103165
        ]
      },
      "properties": {
        "title": "Atwood Innovation Plaza",
        "type": "resource",
        "url": "/pages/atwood-innovation-plaza.md",
        "mapLocation": "Atwood Innovation Plaza, 453 S 700 E, St. George, UT 84770",
        "precision": "exact",
        "provenance": "https://umac.utahtech.edu/art-in-the-city/",
        "region": "St. George",
        "domains": [],
        "focus": "Close or Exit a Business, Entrepreneurship Communities, Funding, International Trade, Aerospace and Defense, Agriculture"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.0266517,
          41.089237
        ]
      },
      "properties": {
        "title": "Clearfield Job Corps",
        "type": "resource",
        "url": "/pages/clearfield-job-corps.md",
        "mapLocation": "Clearfield Job Corps Center, 20 W 1700 S, Clearfield, UT 84016",
        "precision": "exact",
        "provenance": "https://clearfield.jobcorps.gov/contact",
        "region": "Clearfield",
        "domains": [
          "culture-place"
        ],
        "focus": "Late Stage Growth, Aerospace and Defense, Agriculture"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -111.6023339,
          37.7675074
        ]
      },
      "properties": {
        "title": "Escalante City Innovation Center",
        "type": "resource",
        "url": "/pages/escalante-city-innovation-center.md",
        "mapLocation": "Escalante City Innovation Center, 67 N 100 W, Escalante, UT 84726",
        "precision": "exact",
        "provenance": "https://www.escalantecity-utah.com/wp-content/uploads/2024/03/Escalante-General-Plan-.pdf",
        "region": "Escalante",
        "domains": [],
        "focus": "Close or Exit a Business, Entrepreneurship Communities, Funding, International Trade, Aerospace and Defense, Agriculture"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.54747,
          41.62048
        ]
      },
      "properties": {
        "title": "Golden Spike and the First Transcontinental Railroad",
        "type": "work",
        "url": "/pages/golden-spike-transcontinental-railroad.md",
        "mapLocation": "Golden Spike National Historical Park Visitor Center, 6200 N 22300 W, Promontory, UT 84307",
        "precision": "exact",
        "provenance": "https://www.nps.gov/gosp/planyourvisit/directions.htm",
        "region": "Promontory Summit",
        "domains": [],
        "focus": "rail infrastructure, American West, logistics, national integration"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -111.5869919,
          39.3571168
        ]
      },
      "properties": {
        "title": "Snow College - GRIT Center",
        "type": "resource",
        "url": "/pages/snow-college-grit-center.md",
        "mapLocation": "GRIT Center, 151 S Main St, Ephraim, UT 84627",
        "precision": "exact",
        "provenance": "https://omni.snow.edu/offices/grit-center/",
        "region": "Ephraim",
        "domains": [],
        "focus": "Entrepreneurship Communities, Funding, Marketing and Sales, Start a Business, Student, Aerospace and Defense, Agriculture"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.6689,
          41.4375
        ]
      },
      "properties": {
        "title": "Spiral Jetty",
        "type": "work",
        "url": "/pages/spiral-jetty.md",
        "mapLocation": "Spiral Jetty visitor parking and site, Rozel Point, Great Salt Lake, UT",
        "precision": "approximate",
        "provenance": "https://diaart.org/visit/visit-our-locations-sites/robert-smithson-spiral-jetty/main/spiraljetty",
        "region": "Rozel Point, Great Salt Lake, Box Elder County",
        "domains": [],
        "focus": "Land art, Great Salt Lake, site-specific sculpture, contemporary art"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -111.9700095,
          41.2244045
        ]
      },
      "properties": {
        "title": "Startup Ogden",
        "type": "resource",
        "url": "/pages/startup-ogden.md",
        "mapLocation": "Weber State Downtown, 2314 Washington Blvd, Ogden, UT 84401",
        "precision": "exact",
        "provenance": "https://www.weber.edu/maps/locations.html",
        "region": "Ogden",
        "domains": [],
        "focus": "Entrepreneurship Communities, Aerospace and Defense, Agriculture"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.89643,
          38.50416
        ]
      },
      "properties": {
        "title": "Utah FORGE",
        "type": "work",
        "url": "/pages/utah-forge.md",
        "mapLocation": "Utah FORGE well 16A(78)-32, near Milford, UT",
        "precision": "exact",
        "provenance": "https://utahforge.com/wp-content/uploads/2020/06/DataDash-ProvDrillingOperationsJune2020.pdf",
        "region": "Beaver County",
        "domains": [
          "energy"
        ],
        "focus": "enhanced geothermal systems, field laboratories, clean firm power, subsurface engineering"
      }
    }
  ]
}
