// GET /api/search — full-text search over the wiki, for visiting agents.
//
// This is a grep endpoint, not a ranked search engine. research/findings/
// 2026-07-09-search-vs-grep.md measured the alternative: a scored index over
// title+focus+summary saw 13% of the corpus and rewarded term soup, missing the
// ground-truth best match. So: exact, case-insensitive substring matching over full
// page text, and the matching *line* is the result, so the agent judges relevance
// from evidence instead of trusting a score. Documented usage is "make several
// narrow probes (a phrase per probe), not one long query."
//
// Corpus text arrives as a bundled module (api/_search-corpus.mjs, generated by
// scripts/build-search-index.mjs) because Vercel functions cannot read wiki/ from
// disk at request time — the same pattern api/locations.ts uses for map data.
import rawCorpus from './_search-corpus.mjs'

const BASE = 'https://greatutah.work'
const ALLOWED_PARAMS = ['q', 'section', 'type', 'limit', 'hits_per_page']
const PAGE_TYPES = ['venture', 'person', 'helper', 'resource', 'work', 'guide', 'source']
const DEFAULT_LIMIT = 20
const MAX_LIMIT = 200
const DEFAULT_HITS_PER_PAGE = 3
const MAX_HITS_PER_PAGE = 50
const MAX_PAGES_LISTED = 200
const MAX_LINE_CHARS = 300
const MAX_CONTEXT_CHARS = 200
const MIN_QUERY_CHARS = 2
const MAX_QUERY_CHARS = 200
const EXAMPLE = `${BASE}/api/search?q=enhanced+geothermal&type=venture&limit=20`

type CorpusPage = { slug: string; path: string; title: string; type: string; text: string }
type Corpus = { sections: { name: string; pages: number }[]; pages: CorpusPage[] }
type Line = { number: number; text: string; lower: string; section: string | null }
type Entry = { page: CorpusPage; haystack: string; lines: Line[] | null }
type Hit = { index: number; line: Line; at: number }
type Query = Record<string, string | string[] | undefined>

const corpus = rawCorpus as Corpus

const single = (value: string | string[] | undefined) => (Array.isArray(value) ? value[0] : value)
const flatten = (text: string) => text.replace(/\s+/g, ' ').trim()
/** `What They Need Now`, `what-they-need-now`, and `What they need now` are the same section. */
const sectionKey = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()

// Lowercasing 2MB of markdown is worth doing once per process, not once per request.
const prepared = new WeakMap<object, Entry[]>()

function entries(source: Corpus): Entry[] {
  let ready = prepared.get(source)
  if (!ready) {
    ready = source.pages.map((page) => ({ page, haystack: flatten(page.text).toLowerCase(), lines: null }))
    prepared.set(source, ready)
  }
  return ready
}

/** Split lazily — only pages whose text contains the phrase ever pay for this. */
function pageLines(entry: Entry): Line[] {
  if (!entry.lines) {
    let current: string | null = null
    entry.lines = entry.page.text.split('\n').map((raw, index) => {
      // Tolerates the doubled `## Evidence## Evidence` headings present in the corpus.
      const heading = raw.match(/^##[ \t]+(.+)$/)
      if (heading) current = heading[1].split('#')[0].trim() || null
      const text = flatten(raw)
      return { number: index + 1, text, lower: text.toLowerCase(), section: current }
    })
  }
  return entry.lines
}

/** Keep the match visible when a paragraph-long line would otherwise be clipped past it. */
function excerpt(text: string, at: number, needleLength: number) {
  if (text.length <= MAX_LINE_CHARS) return text
  const pad = Math.max(0, Math.floor((MAX_LINE_CHARS - needleLength) / 2))
  const end = Math.min(text.length, Math.max(at + needleLength + pad, MAX_LINE_CHARS))
  const start = Math.max(0, end - MAX_LINE_CHARS)
  return `${start > 0 ? '…' : ''}${text.slice(start, end)}${end < text.length ? '…' : ''}`
}

function neighbour(lines: Line[], index: number, step: number) {
  for (let i = index + step; i >= 0 && i < lines.length; i += step) {
    if (lines[i].text) return lines[i].text.slice(0, MAX_CONTEXT_CHARS)
  }
  return ''
}

function integerParam(query: Query, name: string, fallback: number, max: number, errors: string[]) {
  const raw = single(query[name])
  if (raw == null || raw === '') return fallback
  const value = Number(raw)
  if (!Number.isInteger(value) || value < 1 || value > max) {
    errors.push(`"${name}" must be an integer from 1 to ${max} (got ${JSON.stringify(raw)}); it defaults to ${fallback}.`)
    return fallback
  }
  return value
}

// Reports every problem in one pass, with a working example, so a confused agent
// converges in one round trip (same bar as api/contribute.ts).
function parse(source: Corpus, rawQuery: Query) {
  const errors: string[] = []

  const unknown = Object.keys(rawQuery).filter((name) => !ALLOWED_PARAMS.includes(name))
  if (unknown.length) errors.push(`Unknown parameter(s): ${unknown.join(', ')}. Allowed: ${ALLOWED_PARAMS.join(', ')}.`)

  const q = flatten(String(single(rawQuery.q) ?? ''))
  if (!q) {
    errors.push('"q" is required — the exact phrase to find, matched case-insensitively against the full text of every page.')
  } else if (q.length < MIN_QUERY_CHARS) {
    errors.push(`"q" must be at least ${MIN_QUERY_CHARS} characters (got ${q.length}).`)
  } else if (q.length > MAX_QUERY_CHARS) {
    errors.push(`"q" must be at most ${MAX_QUERY_CHARS} characters (got ${q.length}). This endpoint matches phrases literally, so long queries match nothing — send several narrow probes instead.`)
  }

  const sectionRaw = single(rawQuery.section)
  let section: string | null = null
  if (sectionRaw != null && sectionRaw !== '') {
    const wanted = sectionKey(String(sectionRaw))
    section = source.sections.find((entry) => sectionKey(entry.name) === wanted)?.name ?? null
    if (!section) {
      const known = source.sections.slice(0, 12).map((entry) => `${entry.name} (${entry.pages})`).join(', ')
      errors.push(`Unknown "section": ${JSON.stringify(sectionRaw)}. Sections are the page's \`## Headings\`; most used: ${known}. Case and hyphens are ignored, so section=what-they-need-now works.`)
    }
  }

  const types = String(single(rawQuery.type) ?? '').split(',').map((value) => value.trim().toLowerCase()).filter(Boolean)
  const badTypes = types.filter((value) => !PAGE_TYPES.includes(value))
  if (badTypes.length) errors.push(`"type" contains unknown value(s): ${badTypes.join(', ')}. Allowed: ${PAGE_TYPES.join(', ')} (comma-separate to combine).`)

  const limit = integerParam(rawQuery, 'limit', DEFAULT_LIMIT, MAX_LIMIT, errors)
  const hitsPerPage = integerParam(rawQuery, 'hits_per_page', DEFAULT_HITS_PER_PAGE, MAX_HITS_PER_PAGE, errors)

  if (errors.length) throw new Error(`${errors.join(' ')} Working example: ${EXAMPLE}`)
  return { q, section, types, limit, hitsPerPage }
}

export function searchCorpus(source: Corpus, rawQuery: Query = {}, { baseUrl = BASE } = {}) {
  const { q, section, types, limit, hitsPerPage } = parse(source, rawQuery)
  const needle = q.toLowerCase()
  const wantedSection = section == null ? null : sectionKey(section)

  const matched: { entry: Entry; lines: Line[]; hits: Hit[] }[] = []
  for (const entry of entries(source)) {
    if (types.length && !types.includes(entry.page.type)) continue
    if (!entry.haystack.includes(needle)) continue
    const lines = pageLines(entry)
    const hits: Hit[] = []
    for (let index = 0; index < lines.length; index++) {
      const line = lines[index]
      if (wantedSection != null && (line.section == null || sectionKey(line.section) !== wantedSection)) continue
      const at = line.lower.indexOf(needle)
      if (at < 0) continue
      hits.push({ index, line, at })
    }
    if (hits.length) matched.push({ entry, lines, hits })
  }

  // Count of matching *lines* (grep -c semantics), not a relevance model: it decides only
  // which pages get their lines shown first when `limit` truncates. `pages` keeps full recall.
  matched.sort((a, b) => b.hits.length - a.hits.length || a.entry.page.slug.localeCompare(b.entry.page.slug))

  const matchingLines = matched.reduce((sum, item) => sum + item.hits.length, 0)
  const results = matched.flatMap(({ entry, lines, hits }) => hits.slice(0, hitsPerPage).map(({ index, line, at }) => ({
    path: entry.page.path,
    url: `${baseUrl}${entry.page.path}`,
    title: entry.page.title,
    type: entry.page.type,
    section: line.section,
    line: line.number,
    text: excerpt(line.text, at, needle.length),
    context: { before: neighbour(lines, index, -1), after: neighbour(lines, index, 1) },
    matchingLinesOnPage: hits.length,
  }))).slice(0, limit)

  const words = q.split(' ')
  const note = matched.length === 0
    ? `No page contains the exact phrase "${q}". Matching here is literal (case-insensitive substring over full page text) — nothing is stemmed, scored, or fuzzy-matched.${words.length > 2 ? ` Long queries almost never match: split this into narrow probes such as "${words.slice(0, 2).join(' ')}" and "${words.slice(-2).join(' ')}", then union the results.` : ' Try a shorter or more common phrasing.'}${types.length || section ? ' Dropping the type/section filter widens the search.' : ''} To browse instead, fetch ${baseUrl}/views/index.md.`
    : `Exact, case-insensitive phrase match over full page text — not a ranked search. Pages with more matching lines are shown first (ties alphabetical), at most ${hitsPerPage} lines each; "pages" lists every page that matched, so you keep full recall even when "results" is truncated. Make several narrow probes (a phrase per probe), not one long query, and fetch the url of anything promising.`

  return {
    query: { q, section, types, limit, hitsPerPage },
    coverage: {
      pagesSearched: source.pages.length,
      pagesMatched: matched.length,
      matchingLines,
      returnedLines: results.length,
      pagesListed: Math.min(matched.length, MAX_PAGES_LISTED),
      truncated: matchingLines > results.length,
      note,
    },
    pages: matched.slice(0, MAX_PAGES_LISTED).map(({ entry, hits }) => ({
      title: entry.page.title,
      type: entry.page.type,
      url: `${baseUrl}${entry.page.path}`,
      matchingLines: hits.length,
    })),
    results,
  }
}

// Minimal request/response shapes for a Vercel Node function (no @vercel/node dep).
type Req = {
  method?: string
  query?: Query
  headers?: { host?: string; 'x-forwarded-proto'?: string }
}
type Res = {
  setHeader(name: string, value: string): void
  status(code: number): Res
  json(data: unknown): void
  end(): void
}

export default function handler(req: Req, res: Res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS')
  res.setHeader('Allow', 'GET, OPTIONS')
  res.setHeader('Cache-Control', 'public, max-age=120, stale-while-revalidate=600')
  if (req.method === 'OPTIONS') {
    res.status(204).end()
    return
  }
  if (req.method !== 'GET') {
    res.status(405).json({ ok: false, error: `Use GET. Example: ${EXAMPLE}` })
    return
  }
  try {
    const protocol = req.headers?.['x-forwarded-proto'] || 'https'
    const host = req.headers?.host || 'greatutah.work'
    res.status(200).json({ ok: true, ...searchCorpus(corpus, req.query, { baseUrl: `${protocol}://${host}` }) })
  } catch (error) {
    res.status(400).json({
      ok: false,
      error: { code: 'INVALID_QUERY', message: error instanceof Error ? error.message : String(error) },
      example: EXAMPLE,
    })
  }
}
